export enum EventModes {
  BASKET_BRAWL = 'basketBrawl',
  BIG_GAME = 'bigGame',
  BOSS_FIGHT = 'bossFight',
  BOUNTY = 'bounty',
  BRAWL_BALL = 'brawlBall',
  DUELS = 'duels',
  DUO_SHOWDOWN = 'duoShowdown',
  GEM_GRAB = 'gemGrab',
  HEIST = 'heist',
  HOLD_THE_TROPHY = 'holdTheTrophy',
  HOT_ZONE = 'hotZone',
  INVASION = 'invasion',
  KNOCKOUT = 'knockout',
  LONE_STAR = 'loneStar',
  PAYLOAD = 'payload',
  PRESENT_PLUNDER = 'presentPlunder',
  ROBO_RUMBLE = 'roboRumble',
  SIEGE = 'siege',
  SOLO_SHOWDOWN = 'soloShowdown',
  SUPER_CITY_RAMPAGE = 'superCityRampage',
  TAKEDOWN = 'takedown',
  TROPHY_THIEVES = 'trophyThieves',
  VOLLEY_BRAWL = 'volleyBrawl',
  WIPEOUT = 'wipeout'
}